---
- name: Reload systemd
  systemd:
    daemon_reload: true

- name: Restart Kafka
  systemd:
    name: kafka
    state: restarted

- name: Start Kafka
  systemd:
    name: kafka
    enabled: yes
    state: started
