all:
  hosts:
    bastion:
      ansible_host: 54.12.34.56 # Replace with output from terraform
    jenkins:
      ansible_host: 54.12.34.57 # Replace with output from terraform
  children:
    kafka_brokers:
      hosts:
        kafka1:
          ansible_host: 10.0.10.15 # Private IP of Broker 1
          broker_id: 1
        kafka2:
          ansible_host: 10.0.11.23 # Private IP of Broker 2
          broker_id: 2
        kafka3:
          ansible_host: 10.0.12.44 # Private IP of Broker 3
          broker_id: 3
    kafka_ui:
      hosts:
        kafkaui:
          ansible_host: 54.12.34.58 # Public IP of Kafka UI host
